# Generated by Django 6.0.2 on 2026-02-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
